/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfacegrafica;

import java.awt.event.KeyEvent;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import pacotededados.Calculadora;

/**
 *
 * @author User
 */
public class TelaCalculadora extends javax.swing.JFrame {

    /**
     * Creates new form TelaCalculadora
     */
    Calculadora calc = new Calculadora();
    private boolean calculado = false;

    public TelaCalculadora() {
        initComponents();
        setLocationRelativeTo(null);

    }
    //METODO LIMPA O RESULTADO NA TELA APÓS CLICAR NA PROXIMA AÇAO  

    public void setCalculado() {
        if (calculado || jTextFieldSaida.getText().equals("0")) {
            calculado = false;

            jTextFieldSaida.setText("");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jTextFieldSaida = new javax.swing.JTextField();
        jButtonIgual = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton0 = new javax.swing.JButton();
        jButtonApagar = new javax.swing.JButton();
        jButto3 = new javax.swing.JButton();
        jButtonSubtrair = new javax.swing.JButton();
        jButtonF = new javax.swing.JButton();
        jComboBoxDe = new javax.swing.JComboBox<>();
        jComboBoxPara = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButtonA = new javax.swing.JButton();
        jButtonB = new javax.swing.JButton();
        jButtonC = new javax.swing.JButton();
        jButtonD = new javax.swing.JButton();
        jButtonE = new javax.swing.JButton();
        jButtonConverter = new javax.swing.JButton();
        jButtonVoltar = new javax.swing.JButton();

        jButton3.setText("jButton3");

        jScrollPane1.setViewportView(jEditorPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jTextFieldSaida.setColumns(0);
        jTextFieldSaida.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        jTextFieldSaida.setForeground(new java.awt.Color(51, 51, 51));
        jTextFieldSaida.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldSaida.setText("0");
        jTextFieldSaida.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextFieldSaida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSaidaActionPerformed(evt);
            }
        });
        jTextFieldSaida.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldSaidaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldSaidaKeyTyped(evt);
            }
        });

        jButtonIgual.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonIgual.setForeground(new java.awt.Color(0, 51, 102));
        jButtonIgual.setText("=");
        jButtonIgual.setEnabled(false);
        jButtonIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIgualActionPerformed(evt);
            }
        });

        jButton7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton7.setForeground(new java.awt.Color(0, 51, 102));
        jButton7.setText("7");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(0, 51, 102));
        jButton4.setText("4");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 51, 102));
        jButton1.setText("1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton8.setForeground(new java.awt.Color(0, 51, 102));
        jButton8.setText("8");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(0, 51, 102));
        jButton5.setText("5");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 51, 102));
        jButton2.setText("2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton9.setForeground(new java.awt.Color(0, 51, 102));
        jButton9.setText("9");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton6.setForeground(new java.awt.Color(0, 51, 102));
        jButton6.setText("6");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton0.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton0.setForeground(new java.awt.Color(0, 51, 102));
        jButton0.setText("0");
        jButton0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton0ActionPerformed(evt);
            }
        });

        jButtonApagar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonApagar.setForeground(new java.awt.Color(0, 51, 102));
        jButtonApagar.setText("CE");
        jButtonApagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonApagarActionPerformed(evt);
            }
        });
        jButtonApagar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButtonApagarKeyPressed(evt);
            }
        });

        jButto3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButto3.setForeground(new java.awt.Color(0, 51, 102));
        jButto3.setText("3");
        jButto3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButto3ActionPerformed(evt);
            }
        });

        jButtonSubtrair.setForeground(new java.awt.Color(0, 51, 102));
        jButtonSubtrair.setText("-");
        jButtonSubtrair.setEnabled(false);
        jButtonSubtrair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSubtrairActionPerformed(evt);
            }
        });

        jButtonF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonF.setForeground(new java.awt.Color(0, 51, 102));
        jButtonF.setText("F");
        jButtonF.setEnabled(false);
        jButtonF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFActionPerformed(evt);
            }
        });

        jComboBoxDe.setBackground(new java.awt.Color(0, 51, 102));
        jComboBoxDe.setForeground(new java.awt.Color(0, 51, 102));
        jComboBoxDe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Decimal", "Binário", "Hexadecimal", "Octal" }));
        jComboBoxDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxDeActionPerformed(evt);
            }
        });

        jComboBoxPara.setBackground(new java.awt.Color(0, 51, 102));
        jComboBoxPara.setForeground(new java.awt.Color(0, 51, 102));
        jComboBoxPara.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Binário", "Decimal", "Hexadecimal", "Octal" }));
        jComboBoxPara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxParaActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 102));
        jLabel1.setText("PARA:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 102));
        jLabel2.setText(" DE:");

        jButtonA.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonA.setForeground(new java.awt.Color(0, 51, 102));
        jButtonA.setText("A");
        jButtonA.setEnabled(false);
        jButtonA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAActionPerformed(evt);
            }
        });

        jButtonB.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonB.setForeground(new java.awt.Color(0, 51, 102));
        jButtonB.setText("B");
        jButtonB.setEnabled(false);
        jButtonB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBActionPerformed(evt);
            }
        });

        jButtonC.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonC.setForeground(new java.awt.Color(0, 51, 102));
        jButtonC.setText("C");
        jButtonC.setEnabled(false);
        jButtonC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCActionPerformed(evt);
            }
        });

        jButtonD.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonD.setForeground(new java.awt.Color(0, 51, 102));
        jButtonD.setText("D");
        jButtonD.setEnabled(false);
        jButtonD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDActionPerformed(evt);
            }
        });

        jButtonE.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonE.setForeground(new java.awt.Color(0, 51, 102));
        jButtonE.setText("E");
        jButtonE.setEnabled(false);
        jButtonE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEActionPerformed(evt);
            }
        });

        jButtonConverter.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jButtonConverter.setForeground(new java.awt.Color(0, 51, 102));
        jButtonConverter.setText("CONVERTER");
        jButtonConverter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConverterActionPerformed(evt);
            }
        });

        jButtonVoltar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonVoltar.setForeground(new java.awt.Color(0, 51, 102));
        jButtonVoltar.setText("<--");
        jButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTextFieldSaida))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonA, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonB, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonC, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonD, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonE, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButtonF, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton0, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButto3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButtonIgual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonVoltar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonApagar, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonSubtrair, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(13, 13, 13)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jButtonConverter)
                .addGap(122, 122, 122))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBoxDe, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBoxPara, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButto3, jButton0, jButton1, jButton2, jButton4, jButton5, jButton6, jButton7, jButton8, jButton9, jButtonA, jButtonApagar, jButtonB, jButtonC, jButtonD, jButtonE, jButtonF, jButtonIgual, jButtonSubtrair});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextFieldSaida, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jComboBoxPara, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jComboBoxDe, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1)))
                .addGap(18, 18, 18)
                .addComponent(jButtonConverter)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonApagar)
                        .addComponent(jButtonA)
                        .addComponent(jButtonVoltar))
                    .addComponent(jButtonSubtrair, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton7)
                        .addComponent(jButtonB))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton8)
                        .addComponent(jButton9)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton4)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonC))
                    .addComponent(jButton6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButto3)
                    .addComponent(jButtonD))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton0)
                    .addComponent(jButtonIgual)
                    .addComponent(jButtonF)
                    .addComponent(jButtonE))
                .addGap(61, 61, 61))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButto3, jButton0, jButton1, jButton2, jButton4, jButton5, jButton6, jButton8, jButton9, jButtonApagar, jButtonIgual, jButtonSubtrair});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        setCalculado();
        jTextFieldSaida.setText(jTextFieldSaida.getText() + "9");
        jTextFieldSaida.grabFocus();
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        setCalculado();
        jTextFieldSaida.setText(jTextFieldSaida.getText() + "6");
        jTextFieldSaida.grabFocus();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton0ActionPerformed
        // TODO add your handling code here:

        setCalculado();

        jTextFieldSaida.setText(jTextFieldSaida.getText() + "0");
        jTextFieldSaida.grabFocus();

    }//GEN-LAST:event_jButton0ActionPerformed

    private void jButtonIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIgualActionPerformed
        // TODO add your handling code here
        jTextFieldSaida.grabFocus();
    }//GEN-LAST:event_jButtonIgualActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:

        setCalculado();
        jTextFieldSaida.setText(jTextFieldSaida.getText() + jButton7.getActionCommand());
        jTextFieldSaida.grabFocus();

    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        setCalculado();
        jTextFieldSaida.setText(jTextFieldSaida.getText() + "8");
        jTextFieldSaida.grabFocus();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        setCalculado();
        jTextFieldSaida.setText(jTextFieldSaida.getText() + jButton1.getActionCommand());
        jTextFieldSaida.grabFocus();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        setCalculado();
        jTextFieldSaida.setText(jTextFieldSaida.getText() + jButton2.getActionCommand());
        jTextFieldSaida.grabFocus();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButto3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButto3ActionPerformed
        // TODO add your handling code here:
        setCalculado();
        jTextFieldSaida.setText(jTextFieldSaida.getText() + jButto3.getActionCommand());
        jTextFieldSaida.grabFocus();

    }//GEN-LAST:event_jButto3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        setCalculado();
        jTextFieldSaida.setText(jTextFieldSaida.getText() + jButton4.getActionCommand());
        jTextFieldSaida.grabFocus();

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        setCalculado();
        jTextFieldSaida.setText(jTextFieldSaida.getText() + jButton5.getActionCommand());
        jTextFieldSaida.grabFocus();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButtonApagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonApagarActionPerformed
        // TODO add your handling code here:
        jTextFieldSaida.setText("0");
        jTextFieldSaida.grabFocus();
    }//GEN-LAST:event_jButtonApagarActionPerformed

    private void jTextFieldSaidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSaidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSaidaActionPerformed

    private void jTextFieldSaidaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldSaidaKeyTyped
        // TODO add your handling code here:
        String caracteres = "";

        if (calc.getBase1() == 16) {
            caracteres = "0123456789ABCDEF";
        } else if (calc.getBase1() == 10) {
            caracteres = "0123456789";
        } else if (calc.getBase1() == 8) {
            caracteres = "01234567";
        } else if (calc.getBase1() == 2) {
            caracteres = "01";
        }

        if (!caracteres.contains(evt.getKeyChar() + "")) {
            evt.consume();

        }
    }//GEN-LAST:event_jTextFieldSaidaKeyTyped

    private void jTextFieldSaidaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldSaidaKeyPressed
        // TODO add your handling code here:
        setCalculado();

        if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
            jTextFieldSaida.setText("0");

        }
    }//GEN-LAST:event_jTextFieldSaidaKeyPressed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing


    }//GEN-LAST:event_formWindowClosing

    private void jComboBoxDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxDeActionPerformed
        // TODO add your handling code here:
        setCalculado();
        int base1 = 0;

        if (jComboBoxDe.getSelectedItem() == "Decimal") {
            jTextFieldSaida.setText("0");
            base1 = 10;

            calc.setBase1(base1);

            jButton2.setEnabled(true);
            jButto3.setEnabled(true);
            jButton4.setEnabled(true);
            jButton5.setEnabled(true);
            jButton6.setEnabled(true);
            jButton7.setEnabled(true);
            jButton8.setEnabled(true);
            jButton9.setEnabled(true);
            jButtonA.setEnabled(false);
            jButtonB.setEnabled(false);
            jButtonC.setEnabled(false);
            jButtonD.setEnabled(false);
            jButtonE.setEnabled(false);
            jButtonF.setEnabled(false);

            jTextFieldSaida.grabFocus();

        } else if (jComboBoxDe.getSelectedItem() == "Binário") {
            jTextFieldSaida.setText("0");
            base1 = 2;

            calc.setBase1(base1);

            jButton2.setEnabled(false);
            jButto3.setEnabled(false);
            jButton4.setEnabled(false);
            jButton5.setEnabled(false);
            jButton6.setEnabled(false);
            jButton7.setEnabled(false);
            jButton8.setEnabled(false);
            jButton9.setEnabled(false);
            jButtonA.setEnabled(false);
            jButtonB.setEnabled(false);
            jButtonC.setEnabled(false);
            jButtonD.setEnabled(false);
            jButtonE.setEnabled(false);
            jButtonF.setEnabled(false);

            jTextFieldSaida.grabFocus();

        } else if (jComboBoxDe.getSelectedItem() == "Hexadecimal") {
            jTextFieldSaida.setText("0");
            base1 = 16;

            calc.setBase1(base1);

            jButton2.setEnabled(true);
            jButto3.setEnabled(true);
            jButton4.setEnabled(true);
            jButton5.setEnabled(true);
            jButton6.setEnabled(true);
            jButton7.setEnabled(true);
            jButton8.setEnabled(true);
            jButton9.setEnabled(true);
            jButtonA.setEnabled(true);
            jButtonB.setEnabled(true);
            jButtonC.setEnabled(true);
            jButtonD.setEnabled(true);
            jButtonE.setEnabled(true);
            jButtonF.setEnabled(true);

            jTextFieldSaida.grabFocus();

        } else {
            jTextFieldSaida.setText("0");
            base1 = 8;

            calc.setBase1(base1);

            jButton2.setEnabled(true);
            jButto3.setEnabled(true);
            jButton4.setEnabled(true);
            jButton5.setEnabled(true);
            jButton6.setEnabled(true);
            jButton7.setEnabled(true);
            jButton8.setEnabled(false);
            jButton9.setEnabled(false);
            jButtonA.setEnabled(false);
            jButtonB.setEnabled(false);
            jButtonC.setEnabled(false);
            jButtonD.setEnabled(false);
            jButtonE.setEnabled(false);
            jButtonF.setEnabled(false);

            jTextFieldSaida.grabFocus();

        }


    }//GEN-LAST:event_jComboBoxDeActionPerformed

    private void jComboBoxParaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxParaActionPerformed
        // TODO add your handling code here:
        if (!jTextFieldSaida.getText().equals("0")) {
            setCalculado();
            jTextFieldSaida.grabFocus();
        }

        int base2 = 0;

        if (jComboBoxPara.getSelectedItem() == "Decimal") {
            base2 = 10;
            jTextFieldSaida.grabFocus();
        } else if (jComboBoxPara.getSelectedItem() == "Binário") {
            base2 = 2;
            jTextFieldSaida.grabFocus();
        } else if (jComboBoxPara.getSelectedItem() == "Hexadecimal") {
            base2 = 16;
            jTextFieldSaida.grabFocus();
        } else {
            base2 = 8;
            jTextFieldSaida.grabFocus();
        }

        try {
            calc.setBase2(base2);

            //jTextFieldSaida.grabFocus(); 
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, ex);
        }

    }//GEN-LAST:event_jComboBoxParaActionPerformed

    private void jButtonFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFActionPerformed
        // TODO add your handling code here:
        if (jTextFieldSaida.getText().equals("0")) {
            jTextFieldSaida.setText("");
        }
        jTextFieldSaida.setText(jTextFieldSaida.getText() + jButtonF.getActionCommand());
        jTextFieldSaida.grabFocus();
    }//GEN-LAST:event_jButtonFActionPerformed

    private void jButtonAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAActionPerformed
        // TODO add your handling code here:
        if (jTextFieldSaida.getText().equals("0")) {
            jTextFieldSaida.setText("");
        }
        jTextFieldSaida.setText(jTextFieldSaida.getText() + jButtonA.getActionCommand());
        jTextFieldSaida.grabFocus();
    }//GEN-LAST:event_jButtonAActionPerformed

    private void jButtonBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBActionPerformed
        // TODO add your handling code here:
        if (jTextFieldSaida.getText().equals("0")) {
            jTextFieldSaida.setText("");
        }
        jTextFieldSaida.setText(jTextFieldSaida.getText() + jButtonB.getActionCommand());
        jTextFieldSaida.grabFocus();
    }//GEN-LAST:event_jButtonBActionPerformed

    private void jButtonCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCActionPerformed
        // TODO add your handling code here:
        if (jTextFieldSaida.getText().equals("0")) {
            jTextFieldSaida.setText("");
        }
        jTextFieldSaida.setText(jTextFieldSaida.getText() + jButtonC.getActionCommand());
        jTextFieldSaida.grabFocus();
    }//GEN-LAST:event_jButtonCActionPerformed

    private void jButtonDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDActionPerformed
        // TODO add your handling code here:
        if (jTextFieldSaida.getText().equals("0")) {
            jTextFieldSaida.setText("");
        }
        jTextFieldSaida.setText(jTextFieldSaida.getText() + jButtonD.getActionCommand());
        jTextFieldSaida.grabFocus();
    }//GEN-LAST:event_jButtonDActionPerformed

    private void jButtonEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEActionPerformed
        // TODO add your handling code here:
        if (jTextFieldSaida.getText().equals("0")) {
            jTextFieldSaida.setText("");
        }
        jTextFieldSaida.setText(jTextFieldSaida.getText() + jButtonE.getActionCommand());
        jTextFieldSaida.grabFocus();
    }//GEN-LAST:event_jButtonEActionPerformed

    private void jButtonConverterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConverterActionPerformed
        // TODO add your handling code here:
     

        try {
         
            
            if (jTextFieldSaida.getText().equals(null) || jTextFieldSaida.getText().equals("")
                    || jTextFieldSaida.getText().equals("0")) {
                JOptionPane.showMessageDialog(null, "Favor informar um numero para conversão!");
            } else if (calc.getBase1() == calc.getBase2()) {
                JOptionPane.showMessageDialog(null, "As Bases selecionadas são iguais \n" + "Selecione uma base diferente para conversão!");
            } else {
                String N1 = jTextFieldSaida.getText();
                calc.setN1(N1);
                          
               jTextFieldSaida.setText(calc.mudarBase());
        

                calculado = true;
                jTextFieldSaida.grabFocus();
                 
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, ex);
        }
      
    }//GEN-LAST:event_jButtonConverterActionPerformed

    private void jButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarActionPerformed
        // TODO add your handling code here:
        String voltar = jTextFieldSaida.getText();
        if (voltar.length() == 1) {
            jTextFieldSaida.setText("0");
        } else {
            jTextFieldSaida.setText(voltar.substring(0, voltar.length() - 1));
        }
        jTextFieldSaida.grabFocus();

    }//GEN-LAST:event_jButtonVoltarActionPerformed

    private void jButtonSubtrairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSubtrairActionPerformed
        // TODO add your handling code here:
        jTextFieldSaida.grabFocus();
    }//GEN-LAST:event_jButtonSubtrairActionPerformed

    private void jButtonApagarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButtonApagarKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
            jTextFieldSaida.setText("0");

        }
    }//GEN-LAST:event_jButtonApagarKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCalculadora.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCalculadora.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCalculadora.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCalculadora.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCalculadora().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButto3;
    private javax.swing.JButton jButton0;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JButton jButtonA;
    private javax.swing.JButton jButtonApagar;
    private javax.swing.JButton jButtonB;
    private javax.swing.JButton jButtonC;
    private javax.swing.JButton jButtonConverter;
    private javax.swing.JButton jButtonD;
    private javax.swing.JButton jButtonE;
    private javax.swing.JButton jButtonF;
    private javax.swing.JButton jButtonIgual;
    private javax.swing.JButton jButtonSubtrair;
    private javax.swing.JButton jButtonVoltar;
    private javax.swing.JComboBox<String> jComboBoxDe;
    private javax.swing.JComboBox<String> jComboBoxPara;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldSaida;
    // End of variables declaration//GEN-END:variables
}
